# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp/main.exe"
  full_bin = "./tmp/main.exe"
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "1s"
  delay = 1000
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true