mysql:
  dsn: "user:password@tcp(127.0.0.1:3306)/WaitingToDo?charset=utf8mb4&parseTime=True&loc=Local"
  # 连接池配置
  max_idle_conns: 5        # 最大空闲连接数
  max_open_conns: 20       # 最大打开连接数
  conn_max_lifetime: 1800   # 连接最大生命周期
  conn_max_idle_time: 900  # 连接最大空闲时间

redis:
  addr: "127.0.0.1:6379"
  password: "password"
  db: 0

mail:
  smtp_host: "smtp.163.com"
  smtp_port: 465
  from: "your_username@163.com"
  password: "your_authorization_code"

minio:
  endpoint: "127.0.0.1:9000"
  access_key_id: "your_access_key_id"
  secret_access_key: "your_secret_access_key"

# RabbitMQ配置
rabbitmq:
  dsn: "amqp://guest:guest@localhost:5672/"
  exchange: "social"
  queues:
    friend_request:
      name: "friend_requests"
      routing_key: "friend.request"
    team_request:
      name: "team_requests"
      routing_key: "team.request"

# 日志配置
log:
  level: "info"          # 日志级别: debug, info, warn, error
  filename: "logs/app.log" # 日志文件路径
  max_size: 100          # 单个日志文件最大大小(MB)
  max_backups: 10        # 保留的日志文件数量
  max_age: 30            # 日志文件保留天数
  compress: true         # 是否压缩
  console: true          # 是否输出到控制台