mysql:
  dsn: "user:password@tcp(127.0.0.1:3306)/WaitingToDo?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "127.0.0.1:6379"
  password: "password"
  db: 0

mail:
  smtp_host: "smtp.163.com"
  smtp_port: 465
  from: "your_username@163.com"
  password: "your_authorization_code"

minio:
  endpoint: "127.0.0.1:9000"
  access_key_id: "your_access_key_id"
  secret_access_key: "your_secret_access_key"