mysql:
  dsn: "user:password@tcp(127.0.0.1:3306)/WaitingToDo?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "127.0.0.1:6379"
  password: "password"
  db: 0

mail:
  SMTPHost: "smtp.163.com"
  SMTPPort: 465
  From: "your_username@163.com"
  Password: "your_authorization_code"