mysql:
  dsn: "root:123456@tcp(192.168.163.129:3306)/WaitingToDo?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "192.168.163.129:6379"
  password: "123456"
  db: 0

mail:
  smtp_host: "smtp.163.com"
  smtp_port: 465
  from: "blue2366108@163.com"
  password: "CUdwsU5qu7239tFf"